### PR TITLE
Compiled files and types + type cleanup

### PR DESCRIPTION
**Pull request by LukasDeco**
- Add tsconfig.json
- Run tsc to generate .js files
- Removed debounce function (types were tricky between Nodejs and bun - UI can implement or we can pull in something)

### CODE REVIEW

**Comment by swaggymarie** [comment]
Interesting, there was no way of making it work in ts?

**Comment by Dodecahedr0x** [comment]
I don't believe the js files should be tracked here, they should only be part of the build+publish workflow but can safely be ignored because they can be generated by anyone using the ts files

**Comment by Dodecahedr0x** [comment]
I recommend adding these options in the tsconfig.json as it outputs all compiled file in a  `dist` folder and creates the source maps and declarations for integrating in TS env and better IDE support:
```json
{
  "compilerOptions": {
    "target": "es2019",
    "module": "commonjs",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "skipLibCheck": true,
    "outDir": "dist",
    "sourceMap": true,
    "declaration": true
  }
}
```

I still get an package resolution error for `getTokenMetadata` in `lib/tokens.ts`, is this available in `@solana/spl-token@^0.3.8`?

Otherwise it looks good to me

**Comment by LukasDeco** [comment]
Closing since I have a different branch for this... @Dodecahedr0x you can rebranch off of: https://github.com/metaDAOproject/futarchy-ts/pull/27 for your PR. Not sure if that makes most sense?

**Pull request closed without merging**
